<?php
/**
 * Weather station UI
 *
 * @copyright 2016 Jakub Kaderka
 * @license GNU General Public License, version 2; see LICENSE.txt
 */
defined("IN_APP") or die("Unauthorized access");

function add_graph($id)
{
?>
<div class="graph">
<div id="<?= $id ?>"><?= Lang::get("Enable javascript") ?></div>

<a href="<?= get_link("index") ?>"><?= Lang::get("Week") ?></a>
<a href="<?= get_link("index", false, array('range'=>'month')) ?>"><?= Lang::get("Month") ?></a>
<a href="<?= get_link("index", false, array('range'=>'year')) ?>"><?= Lang::get("Year") ?></a>
</div>
<?php
}
?>

<div id="overview">
<h2><?= Lang::get("Overview") ?></h2>
<table>
	<tr><td><?= Lang::get("Temperature") ?></td><td><?= $temp ?>&deg;C</td></tr>
	<tr><td><?= Lang::get("Wind speed") ?></td><td><?= $wind_speed ?> m/s</td></tr>
	<tr><td><?= Lang::get("Wind direction") ?></td><td><?= $wind_dir ?> &deg;</td></tr>
	<tr><td><?= Lang::get("Relative pressure") ?></td><td><?= $pres ?> hPa</td></tr>
	<tr><td><?= Lang::get("Humidity") ?></td><td><?= $humidity ?> %RH</td></tr>
	<tr><td><?= Lang::get("Rain falls") ?></td><td><?= $rain ?> mm/hod</td></tr>
</table>
<img alt="<?= Lang::get("Webcam") ?>" src="<?= Config::get("files", "webcam") ?>"/>
</div>

<div id="weather_data">
<h2><?= Lang::get("Station location") ?></h2>
<table>
	<tr><td><?= Lang::get("Latitude") ?></td><td><?= Config::get("station", "latitude") ?></td></tr>
	<tr><td><?= Lang::get("Longtitude") ?></td><td><?= Config::get("station", "longtitude") ?></td></tr>
	<tr><td><?= Lang::get("Elevation") ?></td><td><?= Config::get("station", "elevation") ?> m</td></tr>
</table>

<h2><?= Lang::get("Temperature") ?></h2>
<table>
	<tr><td><?= Lang::get("Current") ?></td><td><?= $temp ?>&deg;C</td></tr>
	<tr><td><?= Lang::get("Tendency") ?></td><td><?= $temp_tendency ?>&deg;C/hod.</td></tr>
	<tr><td><?= Lang::get("Dew point") ?></td><td><?= $dew_point ?>&deg;C</td></tr>
	<tr><td><?= Lang::get("Max in 24h") ?></td><td><?= $temp_max ?>&deg;C</td></tr>
	<tr><td><?= Lang::get("Min in 24h") ?></td><td><?= $temp_min ?>&deg;C</td></tr>
	<tr><td><?= Lang::get("Average in 24h") ?></td><td><?= $temp_avg ?>&deg;C</td></tr>
</table>
<?php add_graph("graph_temp") ?>

<h2><?= Lang::get("Wind") ?></h2>
<table>
	<tr><td><?= Lang::get("Speed") ?></td><td><?= $wind_speed ?> m/s</td></tr>
	<tr><td><?= Lang::get("Direction") ?></td><td><?= $wind_dir ?> &deg;</td></tr>
	<tr><td><?= Lang::get("Gusts") ?></td><td><?= $wind_gusts ?> m/s</td></tr>
</table>
<?php add_graph("graph_wind") ?>

<h2><?= Lang::get("Rain falls") ?></h2>
<table>
	<tr><td><?= Lang::get("Intensity") ?></td><td><?= $rain ?> mm/hod</td></tr>
	<tr><td><?= Lang::get("In last hour") ?></td><td><?= $rain_hour ?> mm</td></tr>
	<tr><td><?= Lang::get("Since midnight") ?></td><td><?= $rain_midnight ?> mm</td></tr>
	<tr><td><?= Lang::get("This month") ?></td><td><?= $rain_month ?> mm</td></tr>
	<tr><td><?= Lang::get("This year") ?></td><td><?= $rain_year ?> mm</td></tr>
	<tr><td><?= Lang::get("Latest rainfalls") ?></td><td><?= $rain_date ?></td></tr>
</table>
<?php add_graph("graph_rain") ?>

<h2><?= Lang::get("Pressure") ?></h2>
<table>
	<tr><td><?= Lang::get("Relative pressure") ?></td><td><?= $pres ?> hPa</td></tr>
	<tr><td><?= Lang::get("Tendency") ?></td><td><?= $pres_tendency ?> hPa/hod.</td></tr>
</table>
<?php add_graph("graph_pres") ?>

<h2><?= Lang::get("Humidity") ?></h2>
<table>
	<tr><td><?= Lang::get("Current") ?></td><td><?= $humidity ?> %RH</td></tr>
	<tr><td><?= Lang::get("Tendency") ?></td><td><?= $humidity_tendency ?> %RH</td></tr>
</table>
<?php add_graph("graph_humidity") ?>

<h2><?= Lang::get("Sun") ?></h2>
<table>
	<tr><td><?= Lang::get("UV index") ?></td><td><?= $uv_index ?></td></tr>
	<tr><td><?= Lang::get("Sunrise") ?></td><td><?= $sunrise ?></td></tr>
	<tr><td><?= Lang::get("Sunset") ?></td><td><?= $sunset ?></td></tr>
</table>
<?php add_graph("graph_uv") ?>

</div>


<script type="text/javascript">
window.onload = function show_graphs() {
	temp_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['temp']."]," ;} ?>];
	humidity_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['humidity']."]," ;} ?>];
	pressure_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['pressure']."]," ;} ?>];
	rain_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['rain']."]," ;} ?>];
	wind_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['wind_speed'].",".$item['wind_direction']."]," ;} ?>];
	uv_data = [<?php foreach ($graph as $item) { echo "[new Date(".$item['timestamp']."*1000),".$item['uv']."]," ;} ?>];

	temp = add_graph("graph_temp", temp_data, "<?= Lang::get("Temperature") ?>", "°C");
	humidity = add_graph("graph_humidity", humidity_data, "<?= Lang::get("Humidity") ?>", "%RH");
	pressure = add_graph("graph_pres", pressure_data, "<?= Lang::get("Pressure") ?>", "hPa");
	rain = add_graph("graph_rain", rain_data, "<?= Lang::get("Intensity") ?>", "mm/h");
	uv = add_graph("graph_uv", uv_data, "<?= Lang::get("UV index") ?>", "-");
	wind = add_wind_graph("graph_wind", wind_data,
		["<?= Lang::get("Wind speed") ?>","<?= Lang::get("Wind direction") ?>"],
		["m/s", "°"]);
}
</script>
